package-lock.json, src/main.ts
- Migrate from deprecated Svelte 4 `new App()` to Svelte 5 `mount()` API for component instantiation
=> Migrate to Svelte 5 component API

src/lib/components/WindowControls.svelte, src/lib/components/ui/button.svelte, src/lib/components/ui/card.svelte, src/lib/components/ui/input.svelte, src/lib/components/ui/label.svelte, src/pages/Analytics.svelte, src/pages/Download.svelte, src/pages/Mining.svelte, src/pages/Network.svelte, src/pages/Upload.svelte, tsconfig.node.json
Fixed all file errors in
- WindowControls.svelte
- button.svelte
- card.svelte
- input.svelte
- label.svelte
- Analytics.svelte
- Download.svelte
- Mining.svelte
- Network.svelte
- Upload.svelte
- tsconfig.node.json
=> Resolve errors across multiple files

src/lib/components/ui/button.svelte
fixes onclick attached to Button not being called when clicked
=> Bugfix: Allows common events to propagate to Button component

CLAUDE.md, README.md, src/lib/stores.ts, src/pages/Settings.svelte, src/styles/globals.css, tailwind.config.js
- Remove dark mode theme toggling
- Update markdown files to drop the theme toggling feature
=> Remove dark mode

src-tauri/gen/schemas/windows-schema.json
- Running `npm run tauri dev` on Windows generates the Schema
=> Create Tauri Windows schema

src/pages/Upload.svelte
- Remove unused `Button` import
- Add `role="region"` ARIA attribute to drag-and-drop container for screen reader accessibility
=> Fix two small things in Upload.svelte

src/pages/Account.svelte, src/pages/Mining.svelte
Ensure user input values are valid for account amount and mining controls. Auto correct any invalid values and provide an red error message to the user.
=> Ensure user input values are valid for account amount and mining controls

src/pages/Account.svelte, src/pages/Analytics.svelte, src/pages/Mining.svelte
Previously, the styling for all list items in 'Top Earning Files' and 'Popular Files' in Analytics had the same styling. With this change, the  styling of the top three items provides better visual cues to the user.
=> Analytics file styling

src-tauri/tauri.conf.json, src/App.svelte, src/lib/components/ui/button.svelte, src/pages/Network.svelte, src/pages/Settings.svelte, src/pages/Upload.svelte
- Relocated Mobile Menu: The mobile navigation menu has been moved to prevent it from overlapping with page content.
- Resolved Content Overflow: Fixed layout issues causing content to overflow its container on the Upload, Network, and Settings pages for smaller screen sizes.
- Minimum Screen Size: Added min-width and min-height properties to maintain layout integrity and prevent UI distortion.
=> Mobile UI improvements including contents overflow fixes and added min width&height to avoid UI distortion.

src/pages/Mining.svelte
- Disable Start Mining button when CPU threads or intensity are invalid
- Show inline error messages for invalid inputs
- Add toggle to switch between bar and line charts
- Add line chart scaling and data point display
=> Mining page: Add input validation, line chart and line/bar chart toggle for hash rate history

src/pages/Account.svelte
Fixed the merge conflicts and updating the transaction log.
=> fixed update transaction history on new transactions merge conflicts 

src/pages/Analytics.svelte
Adding Latency Feature in the Analytics tab. This update extends the Analytics tab with a new Network Latency section.
- Displays average, P95, and best latency values derived from proxy nodes.
- Includes a progress bar to visualize current average latency quality (good/ok/poor).
- Adds a recent latency bar chart that updates every 3 seconds alongside bandwidth stats.
- Uses existing proxyNodes.latency values from the store, no schema changes required.
- This improves visibility into network performance by complementing the existing bandwidth metrics.
=> Latency Analytics

src/pages/Account.svelte, src/pages/Mining.svelte
Updated the validation of user input on the Mining and Account pages to provide error messages for empty or otherwise invalid input. Disabled the action buttons if the input is invalid.
=> Fixed issue with validation of user input from earlier PR

src/pages/Mining.svelte
Validates the "CPU Threads" and "Mining Intensity" fields on the mining page. This prevents invalid inputs by showing a red warning and stopping the user from starting the mining process.
=> fix(mining): validate CPU threads and mining intensity inputs

src/pages/Download.svelte, src/pages/Proxy.svelte
checking the newly added node address and preventing adding the same node address multiple times
Before: 
after:
=> Updating Proxy page

src/pages/Account.svelte
For now the `fetchBalance` function should have at least some sample logic to get the account balance. Obviously it and many other functions will need real logic implemented when more things are set up.
=> fix(account): Have sample logic for `fetchbalance` function

src/pages/Settings.svelte
Remove Tauri-only error alert for storage in settings. Added browser support for storage path folder picker
=> fix: storage path for browser

src/pages/Account.svelte
Transaction history now includes full day range
- 03/12/2024
- <img width="1633" height="239" alt="image" src="https://github.com/user-attachments/assets/a6098058-bb1a-4ab1-b8ab-dbdd881ced44" />
- 03/12/2024 to 03/14/2024
- <img width="1630" height="374" alt="image" src="https://github.com/user-attachments/assets/5e96cd78-e583-464f-bf88-77ee207d5de1" />
=> FIX: Account Page, transaction history sorting function

src/pages/Download.svelte, src/pages/Proxy.svelte
Changed the Auto-start button to a toggle shift button that is color coded
before:
after:
=> fixed (Download): changed Auto-Start button to toggle-shift button

src/pages/Download.svelte
- fix queue numbering to show actual position instead of display position
- add dedicated search field for filtering downloads separate from hash input
- hash input now only affects download functionality, not search/filtering
- search properly hides non-matching items instead of just reordering
- Download list shouldn't be searched/sorted while simply typing in a file hash
- Created a search field for separation of concerns
**Before:** 
https://github.com/user-attachments/assets/7573ef06-8880-41e5-8a41-e0ea946b1154
**After:**
https://github.com/user-attachments/assets/9199011d-0487-4b0a-b6e9-d209a3f28e4f
**Before:**
https://github.com/user-attachments/assets/80ae6d41-b43f-418e-87ab-9821c4124780
**After:**
https://github.com/user-attachments/assets/8b312438-c8d2-4186-b2e8-defe3a089290
=> fix (Download): separate search field from hash input and fix queue numbering

src/pages/Account.svelte, src/pages/Download.svelte
The blacklist management section in the create new account tab was taking random addresses without any constraints, so I made sure that valid addresses are accepted.
Before:
After:
=> fix: The blacklist management - Chiral Address Input Box

src/lib/components/GethDownloader.svelte, src/lib/stores.ts, src/pages/Account.svelte, src/pages/Analytics.svelte, src/pages/Download.svelte, src/pages/Network.svelte, src/pages/Proxy.svelte, src/pages/Settings.svelte
- Fix various errors present across `.svelte` files
=> fix: fix all file errors

src/pages/Download.svelte
Before:
After:
The "max current downloads" field is also validated now.
=> refactor: improve download page ui

src/App.svelte, src/lib/services/networkService.ts, src/lib/stores.ts
Implemented a comprehensive real-time network monitoring system that replaces static network status with dynamic monitoring of Geth node, DHT peers, and blockchain peers.
- **`src/lib/services/networkService.ts`**: Real-time network monitoring service
- 3-second interval monitoring
- Parallel checking of Geth, DHT, and blockchain peers
- Robust error handling with graceful fallbacks
- Memory-safe cleanup functions
- **`src/App.svelte`**: Integrated network monitoring in app lifecycle
- **`src/lib/stores.ts`**: Replaced static network status with dynamic monitoring
- **Real-time Updates**: 3-second monitoring intervals
- **Parallel Processing**: Simultaneous Geth, DHT, and blockchain peer checks
- **Error Resilience**: Graceful degradation on API failures
- **Resource Management**: …
=> implement real-time network monitoring system

src/pages/Network.svelte
Before, starting the chiral node would require the user to wait for a short period before visual updates to see the node connected. Implemented minor edits so that starting the node notifies the user that the connection is in progress (matches DHT frontend).
=> feat(network): update start chiral node frontend to match start DHT

src/locales/en.json, src/locales/ko.json, src/pages/Account.svelte
* Replace hard-coded text with i18n keys on Account page.
* Add/update en.json and ko.json for wallet/transfer/transactions/keystore/blacklist.
=> feat(account,i18n): localize Account page and add en/ko strings

src/pages/Network.svelte
- Added copy buttons to Node address, Peer ID and Bootstrap Node for accessibility
- fix: removed redundant dhtPollInterval variable in onMount section triggering unused error
Before:
After:
=> feat(Network): Copy buttons added to Network Page

src/lib/components/WebRTCTest.svelte
- Fix array reactivity by using immutable updates instead of unshift()
- Add comprehensive error handling for async operations
- Validate SDP and ICE candidate JSON before processing
- Fix Svelte template syntax error in placeholder attribute
- Add loading states to prevent concurrent operations
=> fix(webrtc): resolve reactivity and JSON parsing issues in Svelte component

src/App.svelte, src/lib/components/SimpleToast.svelte, src/lib/toast.ts, src/pages/Account.svelte
This PR implements a lightweight toast notification system to improve user experience by providing immediate feedback for user actions.
- `src/lib/toast.ts` - Toast store and utility functions
- `src/lib/components/SimpleToast.svelte` - Toast display component
- `src/App.svelte` - Added SimpleToast component
- `src/pages/Account.svelte` - Integrated toast notifications
- ✅ **Success & Error Notifications** - Green/red styled messages
- ✅ **Auto-dismiss** - 3-second automatic removal
- ✅ **Manual Close** - Click X button to close immediately  
- ✅ **Non-intrusive** - Top-right corner positioning
- ✅ **Responsive** - Works on desktop and mobile
- ✅ **Lightweight** - <100 lines of code total
1. Navigate to Account page
2. Click "Create New Account" → See green success toast
3. Click address …
=> feat: add Toast notification system

src/pages/Analytics.svelte
Before:
No custom date range option for displaying earnings history.
After:
- Adds a custom date range picker to the earnings history chart, allowing users to select arbitrary start and end dates.
- Refactors mock data generation to be dynamic and on-demand, removing the need to pre-load a fixed history on mount.
- Works for both the bars or line option.
=> feat(analytics): add custom date range for earnings chart

src-tauri/src/ethereum.rs
Noticed an issue on the mining page with how the Recent Blocks Found history does not accurately reflect the blocks actually mined in the mining log or the number reported in the rewards section at the top. 
You can see this inconsistency between the 3 below: 
After looking at the code and observing the fronted it seems that while the rewards and mining logs are properly consistent with each other and the updates happening on the wallet page, the Recent Blocks Found is still simulating data. 
To start approaching a fix to having this be accurate rather than simulated data I've added the MinedBlock Struct & get_recent_mined_blocks function, with this newly added struct and function to the backend, we should be able to parse through blocks better and update the recent blocks mined frontend …
=> feat(backend): Added MinedBlock Struct & Recently Mined Blocks Function

package-lock.json, src/lib/stores.ts, src/pages/Network.svelte
Before
After 
Adding ip address validation ( including duplicated address and port, ip format, valid ip range, valid port range)
=> Adding front end IP address validation at Network peer connection. updating the dummy data ip address to include valid port

src/App.svelte, src/locales/en.json, src/locales/ko.json, src/pages/Settings.svelte
Ensure that the saved locale is loaded correctly and bound to DropDown,
so the chosen language no longer resets to English when revisiting the
Settings page.
=> fix(settings): preserve selected language when navigating between pages

src/pages/Settings.svelte
Before clicking save didn't give any feedback, so users have no idea if their settings saved
=> Add success notification to save settings button

src/pages/Mining.svelte
Add pagination for recent blocks found in mining view
- Implement page size selection and navigation controls (prev/next)
- Display current page and total pages with dynamic updates
- Show paginated blocks instead of full list for better UX
- Reset to first page on new block addition or page size change
Before:
After:
=> feat (UI): add pagination to recent blocks found section

src/pages/Mining.svelte
Added comprehensive pool management functionality to the mining interface.
Before
https://github.com/user-attachments/assets/f38c6812-55e8-4a5b-afe0-0ba40d21e359
After
https://github.com/user-attachments/assets/1092ac03-db27-4c25-b6c9-26c088f983dd
- Add pool management functionality (add/edit/delete pools)
- Enhance pool structure to include URL, worker, and password fields  
- Create pool management modal with CRUD operations
- Add 'Manage Pools' button next to pool selection dropdown
- Implement auto-configuration when selecting pools
- Add pool list view with edit/delete actions
- Fix vertical alignment of Manage Pools button with dropdown
- Support custom pool creation and management
- Integrate pool management with existing mining workflow
- All functionality is frontend-only mockup …
=> feat: add pool management mockup with UI improvements

src-tauri/Cargo.lock, src-tauri/src/ethereum.rs
=> fix(mining): fix (Failed to start mining: Geth RPC endpoint is not responding) error

src/pages/Proxy.svelte
- Add dynamic ShieldCheck/ShieldX icons that change based on proxy status
- Implement smooth transitions and animations for better UX
- Enhance toggle switch with mini shield icons and hover effects
- Add status indicators with color-coded visual language (green=secure, red=vulnerable)
- Improve page header with animated shield icon and status badge
- Add pulsing animations for active states and enhanced shadows
- Modernize overall visual design for better presentation
=>  Enhance proxy UI with dynamic shield icons and improved visual feedback

src/pages/Upload.svelte
- Add dynamic file type icons for images, videos, audio, documents, code files, and more
- Implement color-coded file type system for better visual organization
- Enhanced drag and drop area with animated effects and state feedback
- Improved file cards with gradient backgrounds and hover animations
- Added file type preview icons and activity indicators
- Enhanced button styling with hover effects and scale animations
- Improved file hash display with copy functionality
- Added mock upload system for demo purposes when backend is unavailable
=> Enhance Upload page with smart file type detection and animations

src/pages/Download.svelte
**Summary of Changes**
This PR introduces a search-first approach to file discovery and download:
- **New Workflow:**
- **Before:** Clicking "Search and Download" would immediately try downloading a file even if it didn’t exist, resulting in failed downloads.
- **After:** The app now separates Search and Download. Users can see if a file exists first, review its details, and then choose to download.
- **Mock Database for Testing:**
- Added a mock file database with 8 predefined test hashes (both existing and new files).
- Makes it easy to test scenarios like already downloaded files, new downloads, and unknown hashes.
- **Search Result Display:**
- Shows file metadata (name, size, hash).
- Displays peer information (with basic details like peer names, rating, and connection speed).
- …
=> feat: enhance file search functionality with peer information and mock data

src-tauri/src/manager.rs
- Adds the capability to reassemble and decrypt files within the ChunkManager
- Effectively "checks" that our chunking and storage mechanism works correctly by reversing the process
=> feat(manager): Implement file reassembly and decryption

src/pages/Account.svelte
- Support account switching by re-unlocking a different private key.
- Explicit Memory Clearing: Force nullification of sensitive strings
- Browser Security: Clear any localStorage/sessionStorage on logout
=> Support account switching, Explicit Memory Clearing, Browser Security

src/pages/Account.svelte
- created 2FA setup on the accounts page (enable/disable)
- Protects Sensitive Actions
- Simulates Backend Logic
Next steps: implement rust backend implementation
=> feat: started 2FA features, still working on it

README.md, docs/01-system-overview.md, docs/02-architecture.md, docs/03-technical-specifications.md, docs/04-implementation-guide.md, docs/06-security-privacy.md, docs/07-network-protocol.md, docs/08-deployment-guide.md, src/lib/stores.ts, src/pages/Account.svelte
As mentioned today in class, Professor Mu does not want a market. This PR updates the `docs/` so that the Chiral Network is now completely decentralized and operates exclusively through:
- DHT-based file discovery (no market registry)
- Algorithmic reward distribution (no market pricing)
- Direct P2P transactions (no market intermediaries)
- Blockchain consensus (no market servers)
=> docs:  remove market server infrastructure

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/capabilities/default.json, src-tauri/src/commands/proxy.rs, src-tauri/src/dht.rs, src-tauri/src/main.rs, src/lib/services/networkService.ts, src/main.ts, src/routes/proxy-self-test.svelte
Reverts chiral-network/chiral-network#278
=> Revert "feat(nat): HAWKS DHT: NAT traversal (autonat/DCUtR), proxy echo, and Tauri v2 build fixes"

src-tauri/src/dht.rs, src-tauri/src/main.rs
Two small improvements to the proxy self-test view:
* Show the remote peer as online when the connection is established inbound.
* Hide regular DHT peers from the proxy list so it reflects only actual proxy targets/capable peers.
=> proxy-self-test: mark inbound peers online & filter non-proxy nodes

src-tauri/Cargo.toml, src-tauri/src/crypto.rs, src-tauri/src/main.rs, src-tauri/src/manager.rs
* Add erasure coding framework of n=10, t=4, providing fault tolerance if at most 4 of the 14 shards are missing for any given chunk.  
* Adds an additional layer of security as well while allowing data to be outsourced from multiple nodes.   
* Corrected dependency errors, including incorrect module references  
* Fixed building errors, accounting for non-existent function calls/errors.  
* Added `crypto` and `manager` modules to `main.rs`  
* Fixed code issues in `crypto.rs`, including function calls and dependency issues  
* Moved the `crypto.rs` file into `src` to allow for appropriate compilation/dependency fixes from `manager.rs`  
* Adjusted Merkleproof function calls
Notes:
- Current chunk encryption and decryption are failing the test in `manager.rs`, working to fix the code. …
=> feat(manager.rs): Add erasure coding over chunks to support a fault tolerant network (required build/dependency fixes)

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/dht.rs
- adds beetswap and related libraries to cargo.toml to utilize available bitswap protocol implementation
- setup bitswap behaviour events for content exchange
- removed commented out old disconnectPeer handling
=> feat(download): Setup bitswap protocol for content exchange

src-tauri/src/manager.rs
Refactor `manager.rs` for better consistency and removing redundancy:
- Added duplicate code for shard padding, unit tests, and verifying chunk hash.
- Adjusted variable and function names to reflect shard-level encryption/storing/transferring. (was chunk level before)
- Variable names are also now logically reflect their value/intended use.
=> fix(manager): refactor code, deleting unnecessary code and renaming functions/vars

docs/01-system-overview.md
As discussed in lecture today, we will not be moving in the direction of using replication (and nor erasure coding since those go hand in hand) and thus I updated the system_overview doc to keep it consistent and up to date for the class to follow.
=> Chiral network/remove replication from docs

docs/08-deployment-guide.md, src/pages/Account.svelte, src/pages/Mining.svelte
As discussed today in class, replication of the data does not make sense as the files uploaded by our users should be existing on their own nodes.
Also, there was commented out non-functional code that had already had it's functionality implemented either below where the comment was placed or in another file. Deleted these lines to make maintenance and understanding of these files better.
=> chore/docs: Removed Commented Out Code in Mining.Svelte & Account.Svelte. Also got rid of Replication in Doc 08

docs/02-architecture.md
- Remove replication and storage payment references
- Remove storage marketplace and replication model
- Clean up storage payment and replication mentions
=> doc-02: Remove replication (as mentioned in class) and storage payment references

docs/04-implementation-guide.md
Modified changes according to comments from PR#369 so that documentation aligns with our architecture
- Only removed the replication-related parts
- Preserved the operational documentation (Docker, troubleshooting, monitoring)
=> doc-04: removed replication aligning with architecture requirements

src-tauri/src/dht.rs, src-tauri/src/main.rs, src-tauri/src/peer_selection.rs
Enhanced the peer reputation system backend with better scoring.
- Added malicious behavior reporting with severity levels
- Improved scoring formula with bandwidth normalization
- Ready for UI integration
=> feat(reputation): add enhanced peer reputation scoring backend with malicious reporting

src/locales/en.json, src/locales/es.json, src/locales/ko.json, src/locales/zh.json, src/pages/Network.svelte, src/pages/Proxy.svelte, src/pages/Upload.svelte
Added missing translations keys on Chiral Network
=> fix(language): added missing translation keys

.github/workflows/test.yml
* Added caching for Rust dependencies (n=1 10m 12s -> 4m 30s)
First run before caching: 
After caching:
=> feat(ci/cd): cache rust dependencies

src/pages/Reputation.svelte
- Limit peer display to two rows of peers per page 
- Add pagination controls with Previous/Next buttons and page numbers
Before:
After:
=> fix(reputation): limit peer display and add pagination
