chiral-network/chiral-network

src/pages/Settings.svelte

1. Previously the import settings button didn’t trigger the file chooser or import process. Now it correctly opens the file picker, reads the JSON, and applies the settings. 
2. Also fixed the formatting of the file.
Before: Import Settings button is unresponsive
After: After clicking the Import Settings button, it opens the file picker, reads the JSON and applies the settings after opening

Make import settings button functional

---

src/pages/Analytics.svelte
src/pages/Mining.svelte

Unify icon presentation across the app by switching mining/analytics metric icons to Lucide and matching the visual pattern used in Network and Proxy
* Mining: <img width="1712" height="368" alt="image" src="https://github.com/user-attachments/assets/927aa420-7ae8-4ea2-b57d-953b5474e69f" />
* Analytics: <img width="1704" height="378" alt="image" src="https://github.com/user-attachments/assets/7329a838-d12c-4d1b-9702-fa44589d3f38" />
* Mining: <img width="1712" height="375" alt="image" src="https://github.com/user-attachments/assets/1e50d6c3-b721-4a7a-9977-c96dc8d20d5c" />
* Analytics: <img width="1712" height="377" alt="image" src="https://github.com/user-attachments/assets/45fb960c-8b19-4f12-b046-abd1db459fc0" />

Unified site icons (Mining + Analytics) with Lucide

---

src/pages/Upload.svelte

Users can now successfully drag and drop files under the Upload page. Before these changes, dropping a file would open the file in a new tab instead of uploading it.

fix: Users can now drag-and-drop files on Upload page 

---

src/App.svelte

- Previously when you scrolled down on a page such as "Downloads" for example and then switched to another page such as "Mining" for example, the page would remain scrolled down. This PR fixes this.

Page scrolling fix

---

src/pages/Account.svelte

Previously, sending CN tokens only reduced the balance without reflecting the action in the transaction log. This update ensures that the transaction history is updated whenever a transaction occurs.

update transaction history on new transactions

---

src/pages/Account.svelte

The transaction history section now has options to sort transactions by date and type. Users can also select specific dates to view transactions. A reset option was also added to sort transactions by their default state.

Feature: users can now sort their transactions by date and type

---

src/lib/components/ui/progress.svelte
src/pages/Analytics.svelte
src/pages/Download.svelte
src/pages/Upload.svelte

Download Page
- Deleted "Download Complete!" text to avoid redundancy and better UI on Mobile.
Upload Page
- Fixed the file title and size, exceeding the container on Mobile. 
Analytic page
- Fixed the Earning History buttons exceeding the container on Mobile.

fixed styles for mobile on Download, Upload, and Analytic pages.

---

README.md
src-tauri/Cargo.toml
src-tauri/src/main.rs

Add a system tray icon and behavior so the app minimizes to the system tray when the user closes the main window (X). The tray includes a small menu with Show, Hide, and Exit. This change improves UX by preventing accidental quits and enabling quick restore from the tray. Feel free to request changes to the behavior, but this is what I think makes sense for the background operation support.
* Added a system tray icon and menu (Show / Hide / Exit).
* Implemented CloseRequested handling for the main window to prevent close and hide the window (minimize to tray).
* Added handlers for tray left-click to restore/unminimize the main window.

feat(system-tray): implemented basic background operation support

---

src/pages/Analytics.svelte

There was a box appearing at the end of the reputation stars and I fixed it by making sure that the five stars appear while showing the accurate rating within them. 
Before:
After:

fixed: Reputation stars in Analytics

---

src-tauri/src/geth_downloader.rs

- Corrected core-geth download link for Windows in `get_download_url` function
- Binary now downloads for Windows
Before:
After:

fix(network): correct windows download

---

src/lib/stores.ts
src/pages/Mining.svelte

When mining, the blocks found wouldn't show up in the recent block history. 
BEFORE:
AFTER:

Recent blocks found will show when mining

---

src/pages/Account.svelte

The following new `Card` component can be used to encrypt and store a user's credentials in a keystore by invoking the Rust backend function `save_account_to_keystore`. **Team members are working on implementing functionality for sign-in with keystore and web support**

feat(account): Added tauri functionality/frontend for saving keystore to computer

---

src/pages/Settings.svelte

Fix so that Save Changes button is only enabled/ green when the settings are truly changed, and made the Reset to Defaults button red
before:
after:

fix (settings): changed the save changes and reset to defaults button

---

src/pages/Download.svelte

Added a Cancelled section to see previously cancelled tasks, and keeping them in the All section (previous code discarded it).
before:
after:

fix (Download): Added a cancel section and keeping cancelled tasks

---

src/pages/Account.svelte

I fixed the pop message for clearing all of the blacklisted addresses. 
Before: 
After:

fix (account): popup message for clearing all blacklisted messages

---

src/pages/Download.svelte

The status pills in the Download Page have inconsistent coloring when hovering over them. Now, they are a consistent solid color.
Before:
https://github.com/user-attachments/assets/70cc20ea-6a73-49f4-a69c-e6166b123603
After:
https://github.com/user-attachments/assets/88203431-0ed1-4426-a219-1096e14b3975

fix (ui): disable hover on status pills in Download Page

---

src/pages/Settings.svelte

Implemented a user feedback mechanism for the settings import and export functionality to improve user experience.
- Added a persistent notification message that appears upon successful export or import, or on import failure.
- The message informs the user of the action's outcome (e.g., "Settings exported to your browser's download folder" or "Invalid JSON file").
- This feedback remains visible until the user saves the settings again or navigates away from the page, ensuring they have time to read it.

feat(settings): Add feedback for import/export actions

---

src/lib/services/webrtcService.ts
src/lib/stores.ts

- Remove unused Tauri invoke import from `stores.ts`
- Fix `RTCDataChannel.send()` union type error using type assertion

fix: TypeScript errors in `stores.ts` and `webrtcService.ts`

---

src/locales/en.json
src/pages/Analytics.svelte

I made the "latency (recent)" header consistent with all the other headers. 
Before: 
After:

ui (analytics): made all of the headers consistent

---

src/pages/Proxy.svelte

Before:
No sorting mechanism for proxy nodes based on status.
After:
Added a new feature that provides a user dropdown menu to sort the displayed proxy nodes by their connection status (online, connecting, or offline) for better management and visibility.

feat(proxy): add sorting dropdown for proxy nodes

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/dht.rs
src-tauri/src/headless.rs
src/lib/dht.ts
src/pages/Account.svelte
src/pages/Network.svelte

- Added RSA support to `libp2p`
- Enhanced error handling with specific hints for RSA, timeout, and transport failures
- Added connection tracking showing successful/total bootstrap attempts
- Updated default bootstrap node to include full peer ID for reliability
- Improved UI feedback with better error parsing and standalone mode handling
- Changed all instances of "bootstrap node" to "bootstrap nodes" because we may have more than 1 bootstrap node in the future
- Also fix a tiny error in `Account.svelte` where the Amount (Chiral) placeholder literally said "transfer.amount.placeholder"

feat: Enhance DHT Bootstrap Configuration and Terminology

---

src-tauri/src/main.rs
src/pages/Mining.svelte

In a previous PR #168, I added a function into the backend to get recently mined blocks. 
This PR is a follow up to that where I now added a public tauri command called `get_recently_mined_blocks_pub` that is now called in our frontend under the newly created function `appendNewBlocksFromBackend` to grab this information and appropriately update the UI to reflect this. The way this is done is that a Set is created when the mining page is loaded which contains all these recently mined blocks.  
**Before**: 
**After:** 
As you can see from the images above, the issue has been fixed. We may need to consider paginating or changing the way these recent blocks are displayed, but that can be a future PR.

fix(UI/Mining): Fixed Recent Block History To Pull From Backend

---

src/lib/stores.ts
src/pages/Mining.svelte

- Add scrollbar to Recent Blocks Found since previously unlimited blocks will show overfilling the page 
- Add axis labels and blue coloring to the graph of Hash Rate History to look like the graphs on the Analytics page
Before:
After:

feat(Mining): add scrollbar to Recent Blocks Found and make Hash Rate History graph consistent with Analytics page

---

src/pages/Settings.svelte

fix(settings): replace native select with DropDown component for log level

---

.gitignore
src-tauri/build.rs
src-tauri/src/dht.rs
src-tauri/src/ethereum.rs
src-tauri/src/file_transfer.rs
src-tauri/src/headless.rs
src-tauri/src/keystore.rs
src-tauri/src/main.rs
src/lib/dht.ts
src/locales/en.json
src/locales/es.json
src/locales/ko.json
src/locales/zh.json
src/pages/Network.svelte
src/pages/Settings.svelte

This PR improves DHT reliability and observability and tightens settings validation:
* **Health telemetry (backend + UI)** – exposes a lightweight snapshot so users can see when the node last bootstrapped, last peer activity, and recent errors/failures.
* **Graceful DHT shutdown** – avoids orphaned tasks and makes start/stop idempotent.
* **Default bootstraps in headless** – new nodes without config can still join.
* **Settings validation guard** – invalid values no longer persist.
These align with IPFS/Swarm good practices (robust bootstrapping; observable peer lifecycle) and the course goal of shipping small, incremental improvements.
---
* **`get_dht_health` Tauri command** returns `DhtMetricsSnapshot` (peer count, timestamps for last bootstrap/peer-event/error, and recent bootstrap …

feat(dht): add health telemetry API + UI;  grace shutdown; default bootstraps; settings validation

---

src/App.svelte
src/pages/Proxy.svelte

* Removed the default label so that only one label is shown when hovering over a section when sidebar menu is collapsed.
* Aligned dropdown button next to "Proxy Nodes" in the Proxy Network section to be similarly formatted with Network and Settings sections.

Fix bug in collpased sidebar menu in which two labels were shown; Align dropdown button styling in Proxy section with Settings section

---

src/pages/Account.svelte

- Added button that lets user import private key from wallet json file instead of having to copy paste it
Before:
After:
Note: mouse is hovered over button (cursor not shown in screenshot)
Shows error message when selected file is not in proper format and doesn't have privateKey field:

feat(Account): Add button to import private key from exported wallet json file

---

src/pages/Upload.svelte

- Switched file hash calculation to use browser-based SHA-256 for each uploaded file ( this should be more secure)
- Removed backend upload and Tauri integration; all file processing now happens client-side.
- Updated file upload logic to improve reliability and transparency for users.

Bugfix: adding and dropping files work again 

---

src/pages/Account.svelte
src/pages/Settings.svelte
src/pages/Upload.svelte

- Fixed `Account.svelte` translation parameters by wrapping insufficient balance error values in `{ values: { ... } }` format
- Made Settings search bar full-width by removing `max-w-md` class constraint
- Added missing closing </button> tag in `upload.svelte`
- Removed unused sectionKeys object and resetSection function from `Settings.svelte`
Before:
After:

fix: Fix various UI/UX Issues and Translation Parameters

---

src/lib/dhtHelpers.d.ts
src/lib/dhtHelpers.js
src/pages/Network.svelte
tests/dhtHelpers.test.mjs

Prevents the Network page from continuing to show a “Retry” state after a successful DHT connect by resetting the attempts counter.
1) Start the desktop app, go to Network → DHT.
2) Connect once; after success the button label should revert to “Connect to DHT Network” and attempts reset to 0.
3) Disconnect and reconnect to confirm the behavior is consistent.
- `node --test tests/dhtHelpers.test.mjs`

fix(ui): reset DHT retry label after successful connect

---

src-tauri/src/dht.rs
src/lib/dht.ts
src/locales/en.json
src/locales/es.json
src/locales/ko.json
src/locales/zh.json
src/pages/Network.svelte

Expose the node’s live listen multiaddrs in DHT health and render them on Network → DHT with copy actions. This helps verify port configuration and advertised endpoints, especially with multi-instance setups and user-configurable `dhtPort`.

feat(network): surface DHT listen addresses

---

src-tauri/Cargo.toml
src-tauri/crypto.rs
src-tauri/src/manager.rs

- crypto.rs implements a hybrid encryption scheme to securely encrypt a file's symmetric AES key using the recipient's X25519 public key. 
- Bundles the encrypted key with the necessary data for the recipient to decrypt it with their private key, ensuring end-to-end security for file transfers.

feat: chunk encryption with the recipient's public key

---

src/lib/stores.ts
src/pages/Account.svelte
src/pages/Mining.svelte

Previously while mining had properly updated the wallet with the Chiral earned, there was no clear way to identify how much Chiral you were earning/earned from the mining. To resolve this, we decided to add the results of a mining session to the transaction history with how many blocks were mined. 
This can be seen in this screenshot here: 
Not entirely sure how the card/receipt itself should look for this kind of recorded transaction and whether the mining page should be showing total blocks mined, or if it should showcase the blocks only from the ongoing mining session. That could be worth looking into for future PRs.  
To accomplish this we moved the Transaction Interface out of account and into stores.ts as we're expanding the use of transactions to record payouts from mining sessions …

feature(UI): Added Mining Session Payouts To Transaction History

---

src-tauri/src/manager.rs

- restore the missing comma in `ChunkInfo` so the struct parses correctly
- import `rand::RngCore` so `OsRng.fill_bytes` links during chunk encryption
1. Ensure the frontend dist folder exists so Tauri’s macro resolves: `mkdir -p dist`
2. Run `cargo check` inside `src-tauri/`
3. From the repo root, run `node --test`
_No UI changes—screenshots not required._

fix(manager): repair chunk struct and rng usage

---

src-tauri/src/geth_downloader.rs

- correct the macOS x86_64 download URL to use the `core-geth-osx` archive
- keep both macOS architectures aligned on the macOS bundle so Intel users receive a valid binary
1. Ensure the frontend dist folder exists: `mkdir -p dist`
2. Run `cargo check` inside `src-tauri/`
3. (Optional) `curl -I https://github.com/etclabscore/core-geth/releases/download/v1.12.20/core-geth-osx-v1.12.20.zip` to
confirm the resolved file
_No UI changes—screenshots not required._

fix(geth): point intel mac download to macos archive

---

src/lib/components/wallet/AccountList.svelte
src/pages/Account.svelte

Before, the HD wallet would appear to the right of the "Chiral Network Wallet" card, but this created some UX experiences:
- There was unnecessary empty blank space under the wallet info card
- The user could keep deriving keys from the recovery phrase, create a long list that extends downwards and requires a lot fo scrolling.
After:
- The HD wallet is now located under the wallet info and send coins cards, allowing for better UX. 
- The HD wallet also transforms into a dropdown if there are more than 3 accounts. 
- The select button also greys out if a certain account is currently selected.

feat(account): update UI of HD wallet for better UX

---

src-tauri/src/main.rs
src/pages/Mining.svelte

- The temperature reading tries to get the real temperature from the backend every 2 seconds and shows an actual reading if hardware sensors work on Windows (I believe this is only implemented for Mac as of now)
- The temp reading shows "not available" if no hardware sensors are found; the fake estimates are removed entirely.
- The temp reading shows "detecting temperature sensors" on an initial load
- Add color levels (green, yellow, red) to indicate good vs bad temps
Some pics:

feat(mining): add temperature sensor for Windows

---

src/pages/Proxy.svelte

fix(proxy): removed hover animations to be consistent with other cards

---

src/pages/Mining.svelte

Eliminated unused `sessionStartRewards` and `sessionStartBlocks` variables that were duplicating data already tracked in the `miningState`.

fix(mining): fix `.svelte` errors for unused variables

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs
src/pages/Mining.svelte

The Temperature field in the Mining tab only worked correctly for Windows and Mac before.
Now, it works for Linux as well.
We use multiple different sources so we can fall back from more reliable monitoring sources to less reliable ones.
In addition, the final temperature fallback used to be randomized values.
Now, we instead simply print "N/A" if all else fails.

fix(mining): temperature for linux

---

src/pages/Mining.svelte

Before:
Only the Celsius option for temperature is available.
After: 
The user can toggle between Celsius and Fahrenheit options.

feat(mining): Add Fahrenheit option to temperature display

---

src-tauri/src/main.rs

The Geth RPC URL ("http://127.0.0.1:8545") was previously hardcoded in `is_geth_rpc_ready` and `start_miner`
This commit introduces an `rpc_url` field to the `AppState` struct to act as a single source of truth for the Geth endpoint.
- Adds `rpc_url` to `AppState` and initializes it on startup.
- Modifies `is_geth_rpc_ready` to accept the application state and use the configured URL.
- Updates `start_miner` and other RPC call sites to read the URL from the state.

refactor(geth): Centralize Geth RPC URL in application state

---

src/pages/Download.svelte

Improves user experience by adding a "Retry" button to downloads that have a status of 'failed' or 'canceled'.
Previously, users had no direct way to restart a download that did not complete successfully. This change provides a simple one-click action to re-queue the file for download.
This commit introduces:
- A `retryDownload` function that removes the old entry and adds a new one to the download queue with a 'queued' status.
- A "Retry" button in the UI that is conditionally displayed for items with a 'failed' or 'canceled' status.
- Clear Finished Downloads:
- An individual "Clear" (X) button has been added to all finished items (completed, failed, canceled) to remove them from the list one by one.
- A "Clear All Finished" button is now available to remove all non-active downloads at …

feat(download): Add retry functionality for failed/canceled downloads

---

src/pages/Account.svelte

This fix make sure that when a new wallet account is created, the blacklist is initialized as an empty array instead of containing demo data. 
Before: 
After:

fix(account): reset blacklist on new account creation

---

src-tauri/src/dht.rs
src-tauri/src/ethereum.rs
src/pages/Mining.svelte

Before: 
- No estimated time to block calculated while mining
- Block rewards were fixed at 2 Chiral instead of 5.
After:
- Aligns all reward logic with the intended 5 Chiral: Updated the value in the backend (`ethereum.rs`) and updated the frontend Total Rewards calculation.
- Implemented and formatted the Estimated Time to Block (ETB) calculation on the Mining page.
- Resolved module conflicts in `dht.rs` to ensure a clean build.

fix(mining): Standardize rewards to 5 Chiral and enable Estimated Time to Block calculation

---

src-tauri/src/ethereum.rs
src/pages/Mining.svelte

- Fixed blocks found counter stopping at 101
- debug console.log statements
- Increased search range in get_mined_blocks_count from 100 to 1000 blocks
- This allows the block counter to continue growing instead of being limited by recent block range
before
after

fix: increase block search range from 100 to 1000 blocks

---

docs/04-implementation-guide.md
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/dht.rs
src-tauri/src/encryption.rs
src-tauri/src/ethereum.rs
src-tauri/src/headless.rs
src-tauri/src/keystore.rs
src-tauri/src/main.rs
src-tauri/src/net/proxy_server.rs
src/lib/dht.ts
src/locales/en.json
src/pages/Network.svelte

- mount libp2p AutoNAT v2 client/server (feature-gated in rust-
libp2p) so the desktop node can detect reachability and emit libp2p-
style NatStatus events; mirrors go-libp2p autonat.go semantics
example wiring.
- extend DhtMetricsSnapshot/commands/headless flags with
reachability state, observed external addrs, and history so
operators can audit probe outcomes (--disable-autonat, --autonat-
probe-interval, --autonat-server, --show-reachability); headless
logs follow punchr’s “summary per probe” approach for future
ingestion.
- surface a Network → DHT “Reachability” card (Kubo vocabulary:
Direct/Relayed/Unknown) with confidence badge, observed address
chips, probe history, and toast notifications on state changes,
making AutoNAT decisions visible in the GUI.
- refresh docs to explain how …

feat(nat): surface reachability telemetry and UI card

---

src-tauri/src/main.rs
src-tauri/src/manager.rs

The `reassemble_and_decrypt_file` function would incorrectly return a success status when provided with an insufficient number of shards for reconstruction. 
This commit handles empty chunk manifests, ensuring the function behaves correctly for zero-chunk files.

fix(manager): Correct file reassembly logic for missing shards

---

src/lib/services/server/server.cjs
src/lib/services/signalingService.ts
src/pages/Network.svelte

**Changes**
- add WebSocket signaling server (`server.cjs`) on port 9000 for peer discovery
- implement peer registration, message routing, and disconnection handling
- update `SignalingService.ts` client to interact with the signaling server
- update `Network.svelte` to:
- initialize signaling service on mount
- discover peers dynamically via WebSocket
- replace mock peer connections with WebRTC sessions
- add connection state monitoring and toast notifications
- add error handling and validation for WebSocket and WebRTC states

fix(webrtc): peer connection

---

src-tauri/src/main.rs

The application frequently fails to start Geth with the error "Fatal: Failed to create the protocol stack: datadir already used by another process". This occurs when:
- The application crashes or is force-closed without properly terminating Geth
- Stale lock files (`LOCK` and `geth.ipc`) are left in the data directory
- Previous cleanup logic only worked on Unix systems
Added Windows-specific cleanup logic in the application setup phase:
- Terminates any orphaned `geth.exe` processes using `taskkill`
- Removes stale `LOCK` file from the data directory if present
- Removes stale `geth.ipc` file from the data directory if present
This complements the existing Unix cleanup code (`pkill`) to ensure cross-platform reliability.
- Verified that stale lock files are properly removed on Windows …

fix: Clean up stale Geth lock files on Windows startup to prevent "datadir already used" errors

---

src-tauri/src/manager.rs

Implement local deduplication for encrypted shards
- Before saving an encrypted shard, check if a file with the same hash already exists in the storage directory.
- Skip writing the shard if it already exists, but always update metadata and cache.
- This prevents redundant storage of identical shards, saving disk space and improving efficiency.

feat: implement local deduplication for encrypted shards

---

src/lib/services/signalingService.ts

App crashed with `TypeError: Illegal invocation`. when starting a download or retrying existing downloads. This prevented any P2P downloads from even attempting to start.
- In `signalingService.ts`, the `createClientId()` function was storing `crypto.randomUUID` in a variable before calling it. This caused the function to lose its `this` context, breaking the Web Crypto API call.
- Changed line 6-7 to call `globalThis.crypto.randomUUID()` directly instead of storing it first
- Preserves proper `this` binding for the crypto API

Fix illegal invocation error preventing downloads from starting

---

run-bootstrap.sh

This PR updates the bootstrap-node-runner.sh script to fully support all command-line flags defined in the CliArgs Rust struct found in "headless.rs". Previously, only a subset of options were exposed via the shell script; this update ensures feature parity between the Rust CLI and the shell wrapper, allowing users to configure the bootstrap node entirely through command-line arguments or environment variables.
Added support for the following CLI options (These flags are all optional):
--secret
--disable-autonat
--autonat-probe-interval
--autonat-server
--socks5-proxy
--show-multiaddr
--show-reachability
--show-downloads

Add support for all CliArgs flags in the bootstrap node shell script

---

src-tauri/src/commands/proxy.rs
src-tauri/src/main.rs
src/lib/proxy.ts
src/pages/Proxy.svelte
vite.config.ts

[Resolve race condition]
The first echo sent from a peer after connecting would not appear. Subsequent echos, or echos from the remote peer, worked correctly.
This was caused by a race condition where an echo could be sent before the initProxyEvents() function had finished setting up the necessary event listeners to capture and display outgoing messages.
By adding 'await' to the initProxyEvents() call, we ensure that the event handling system is fully initialized before any user actions, like sending an echo, can proceed. This guarantees that all sent messages are captured.
[Enable proxy node removal]
The remove button for proxy nodes is now functional. Previously, clicking the button had no effect, and the node was not removed from the configuration. This issue has been resolved, and the …

fix(proxy): Resolve race condition

---

src/lib/components/download/DownloadSearchSection.svelte

Before:
The Download page would load and immediately perform a file search even without user input. This led to a timeout message despite the user not searching for any downloaded files.
After:
The Download page loads without any unexpected searches not performed by the user.
- Decouples the main search state from persistent search history (dhtSearchHistory) during component initialization.
- This prevents the component from automatically loading the hash and 'error' status of the last failed search on mount, which unintentionally triggered a new, immediate, and failed search.
- The component now loads into a clean, 'pending' state, waiting for user input.

fix(download): Prevent automatic timeout error on initial load of the Download page

---

docs/08-deployment-guide.md

Doc Currently Gives Impression of Community and Professional Support, so replaced those sections with TBD until the project is completely finished since at the current moment this doesn't really exist. Additionally, updated the documentation links to properly point back to our repo.  
Was originally going to change the deployment guide by removing the notion of storage nodes but refrained from doing so until further confirmation. With the current understanding the client is it's own storage node so mentioning it may give the wrong idea. There are other misc. things in this doc that may need to be removed in the future (I have no idea if we will have a chiral-CLI) but that can wait.

docs-08: Removed Professional & Community Support, Fixed documentation links to point back to GitHub! 

---

docs/03-technical-specifications.md

Rephrase the Storage Nodes section in Node Requirements: As per the professor, there is no conceptual difference between storage nodes and normal nodes. A storage node would be a server machine that keeps running our software, allocates disk space for storing file chunks, registers availability in the DHT.
Removed Transaction types - Storage Request and Storage Proofs: Chiral Network currently operates without a storage marketplace. All nodes store their own file chunks locally, and there are no on-chain transactions for requesting or proving storage.

doc-03: Rephrased and Clarified Storage Nodes Sections

---

docs/02-architecture.md

I updated both the upload and download data flow diagrams in document 2 to reflect removals in inconsistent project understanding.
Before (Upload and Download):
After (Upload and Download):

Chiral network/doc02 fix upload data flow diagram

---

docs/02-architecture.md

Added BitTorrent-style parallel download flow, pricing configuration step in upload flow . 
The download flow support: 
- Supports parallel downloads from multiple seeders
- Includes provider selection 
- Performance tracking with blacklist capability
- Per-chunk payment distribution
After talking with Professor Shuai before, he said that the system should allow clients to select providers from a list

Doc2: Add BitTorrent-Style Download Flow

---

src/pages/Account.svelte

- fix reference error for wallet service is not defined
Before:
After:

fix(Account): fix reference error for wallet service is not defined

---

src/pages/Network.svelte

[Synchronized port number]
The DHT port number was hardcoded to 4001 on component mount, causing the UI to display the wrong port when reconnecting to an already-running DHT service on a different port. 
Now syncs the actual port from the DhtService when mounting the component.
Problem:

fix(network): Synchronized port number when re-entering Network page

---

src/lib/components/GeoDistributionCard.svelte

Geographic distribution now only shows up to top 3 regions.
**Before**
**After**

fix(network): limit geographic distribution to top 3 regions

---

src-tauri/src/dht.rs

- Detect /p2p-circuit components in NewListenAddr events
- Call swarm.add_external_address for relay circuit addresses and log the advertisement

feat(relay): advertise circuit address on new listener

---

src/routes/proxy-self-test.svelte

UI before:
UI after:
This change was made to align the styling of the dropdown with other
dropdowns in the application, ensuring a consistent user experience.

refactor(ui): Use DropDown component in proxy-self-test
